# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "console.fullname" . }}-config
  labels:
    app: {{ template "console.fullname" . }}
    chart: {{ template "console.chart" . }}
    release: {{ template "console.fullname" . }}
    heritage: {{ .Release.Service }}
data:
  ui-config.json: |-
    {
      "icpText": "{{ .Values.consoleheader.uiconfig.icpText }}",
      "about": {
        "path": "{{ .Values.consoleheader.uiconfig.about.text }}"
      },
      "header": {
        "path": "{{ .Values.consoleheader.uiconfig.header.path }}",
        "width": "{{ .Values.consoleheader.uiconfig.header.width }}",
        "height": "{{ .Values.consoleheader.uiconfig.header.height }}"
      }
    }
