# Copyright (c) 2020 Red Hat, Inc.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ibm-icp-management
    icp.management.ibm.com/auth-type: access-token
    icp.management.ibm.com/configuration-snippet: |
        add_header 'X-XSS-Protection' '1' always;
        add_header Content-Security-Policy "default-src 'none'; font-src 'unsafe-inline' 'self'; script-src 'unsafe-inline' 'self' blob: cdn.segment.com fast.appcues.com; connect-src 'self' https://api.segment.io wss://api.appcues.net https://notify.bugsnag.com; img-src * data:; frame-src 'self' https://my.appcues.com; style-src 'unsafe-inline' 'self' https://fast.appcues.com";
  name: {{ template "console.fullname" . }}
  labels:
    app: {{ template "console.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{.Release.Service | quote }}
    chart: {{ template "console.chart" . }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ template "console.fullname" . }}
          servicePort: 3000
        path: /header/
