name: Lint the Helm chart

on:
  pull_request:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    env:
      # where the chart lies within the repo
      CHART_PATH: stable/console-chart
    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.4

      - name: Lint chart
        run: |
          helm version
          helm lint "$CHART_PATH"
